/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : anarrietam
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include <stm32f0xx.h>

#include "GPIOxDriver.h"
#include "BasicTimer.h"

GPIO_Handler_t hanlderLedPrueba = {0};
BasicTimer_Handler_t handlerTimerLed = {0};

//Header de las funcionas a implementar en el main
void initConfig(void);

int main(void)
{
	initConfig();
    while(1){

    }
}

void initConfig(void){

	hanlderLedPrueba.pGPIOx                             = GPIOA;
	hanlderLedPrueba.GPIO_PinConfig.GPIO_PinNumber      = PIN_5;
	hanlderLedPrueba.GPIO_PinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
	hanlderLedPrueba.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	hanlderLedPrueba.GPIO_PinConfig.GPIO_PinOPType      = GPIO_OTYPE_PUSHPULL;
	hanlderLedPrueba.GPIO_PinConfig.GPIO_PinSpeed       = GPIO_OSPEED_HIGH;

	GPIO_Config(&hanlderLedPrueba);
	GPIO_WritePin(&hanlderLedPrueba, SET);

	handlerTimerLed.ptrTIMx                          = TIM14;
	handlerTimerLed.TIMx_Config.TIMx_mode            = BTIMER_MODE_UP;
	handlerTimerLed.TIMx_Config.TIMx_period          = 250;
	handlerTimerLed.TIMx_Config.TIMx_speed           = BTIMER_SPEED_1ms;
	handlerTimerLed.TIMx_Config.TIMx_interruptEnable = BTIMER_INTERRUPT_ENABLE;

	BasicTimer_Config(&handlerTimerLed);

}

void BasicTimer14_Callback(void){
	GPIOxTooglePin(&hanlderLedPrueba);
}
