/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : anarrietam
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include <stm32f0xx.h>

#include "GPIOxDriver.h"
#include "BasicTimer.h"
#include "USARTxDriver.h"
#include "PwmDriver.h"

GPIO_Handler_t hanlderLedPrueba = {0};
BasicTimer_Handler_t handlerTimerLed = {0};

// Prueba del usart
USART_Handler_t USARTHandler = {0};
GPIO_Handler_t  PINTX        = {0};
GPIO_Handler_t  PINRX        = {0};

// Prueba PWM
GPIO_Handler_t handlerPWMPin = {0};
PWM_Handler_t  handlerPWM    = {0};

// variables
char rxChar = 0;
//Header de las funcionas a implementar en el main
void initConfig(void);

int main(void){
	initConfig();
	// Se imprime el mensaje de inicio
	writeMsg(&USARTHandler, "Hola");


    while(1){
    	}
}

void initConfig(void){

	hanlderLedPrueba.pGPIOx                             = GPIOA;
	hanlderLedPrueba.GPIO_PinConfig.GPIO_PinNumber      = PIN_5;
	hanlderLedPrueba.GPIO_PinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
	hanlderLedPrueba.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	hanlderLedPrueba.GPIO_PinConfig.GPIO_PinOPType      = GPIO_OTYPE_PUSHPULL;
	hanlderLedPrueba.GPIO_PinConfig.GPIO_PinSpeed       = GPIO_OSPEED_HIGH;

	GPIO_Config(&hanlderLedPrueba);
	GPIO_WritePin(&hanlderLedPrueba, SET);

	handlerTimerLed.ptrTIMx                          = TIM16;
	handlerTimerLed.TIMx_Config.TIMx_mode            = BTIMER_MODE_UP;
	handlerTimerLed.TIMx_Config.TIMx_period          = 250;
	handlerTimerLed.TIMx_Config.TIMx_speed           = BTIMER_SPEED_1ms;
	handlerTimerLed.TIMx_Config.TIMx_interruptEnable = BTIMER_INTERRUPT_ENABLE;

	BasicTimer_Config(&handlerTimerLed);

	USARTHandler.ptrUSARTx                           = USART1;
	USARTHandler.USART_Config.USART_mode             = USART_MODE_RXTX;
	USARTHandler.USART_Config.USART_baudrate         = USART_BAUDRATE_115200;
	USARTHandler.USART_Config.USART_parity           = USART_PARITY_NONE;
	USARTHandler.USART_Config.USART_stopbits         = USART_STOPBIT_1;
	USARTHandler.USART_Config.USART_datasize         = USART_DATASIZE_8BIT;
	USARTHandler.USART_Config.USART_enable_IntRx     = USART_RX_INTERRUPT_ENABLE;
	USART_Config(&USARTHandler);

	PINTX.pGPIOx                            = GPIOB;
	PINTX.GPIO_PinConfig.GPIO_PinNumber     = PIN_6;
	PINTX.GPIO_PinConfig.GPIO_PinMode       = GPIO_MODE_ALTFN;
	PINTX.GPIO_PinConfig.GPIO_PinAltFunMode = AF0;
	GPIO_Config(&PINTX);

	PINRX.pGPIOx                            = GPIOA;
	PINRX.GPIO_PinConfig.GPIO_PinNumber     = PIN_3;
	PINRX.GPIO_PinConfig.GPIO_PinMode       = GPIO_MODE_ALTFN;
	PINRX.GPIO_PinConfig.GPIO_PinAltFunMode = AF1;
	GPIO_Config(&PINRX);

	handlerPWMPin.pGPIOx                             = GPIOB;
	handlerPWMPin.GPIO_PinConfig.GPIO_PinNumber      = PIN_5;
	handlerPWMPin.GPIO_PinConfig.GPIO_PinMode        = GPIO_MODE_ALTFN;
	handlerPWMPin.GPIO_PinConfig.GPIO_PinOPType      = GPIO_OTYPE_PUSHPULL;
	handlerPWMPin.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	handlerPWMPin.GPIO_PinConfig.GPIO_PinSpeed       = GPIO_OSPEED_HIGH;
	handlerPWMPin.GPIO_PinConfig.GPIO_PinAltFunMode  = AF1;
	GPIO_Config(&handlerPWMPin);

	handlerPWM.ptrTIMx                               = TIM3;
	handlerPWM.config.channel                        = PWM_CHANNEL_2;
	handlerPWM.config.periodo                        = 2000;
	handlerPWM.config.duttyCicle                     = 1000;
	handlerPWM.config.prescaler                      = 8000;
	pwm_Config(&handlerPWM);
	enableOutput(&handlerPWM);
	startPwmSignal(&handlerPWM);


}

void BasicTimer16_Callback(void){
	GPIOxTooglePin(&hanlderLedPrueba);

}

void usart1Rx_CallBack (void){
	rxChar = getRxData();
	writeChar(&USARTHandler, rxChar);
}


